config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	# get 'bookers/show' => 'bookers#show'

    root :to => 'bookers#top'
    get '/bookers/about' => 'bookers#about'
    # get '/top' => '', as: 'bookers_top'
  	#post '/bookers' => 'bookers#create'
  	#get '/bookers/index' => 'bookers#index'
  	#get '/bookers/:id' => 'bookers#show', as: 'booker'
  	#patch '/bookers/:id' => 'bookers#update', as: 'update_booker'
  	#get '/bookers/:id/edit' => 'bookers#edit', as: 'edit_booker'
     resources :bookers

     resources :users, only: [:show, :edit, :update, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booker.rb
class Booker < ApplicationRecord
	validates :title, presence: true
  	validates :body, presence: true, length: { maximum: 200 }

  	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookers

  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :user_body, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  	before_action :configure_permitted_parameters, if: :devise_controller?
  	protected

  	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
  	end

  	def after_sign_in_path_for(resource)
  		user_path(resource)
  	end
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController
  def top
  end
  def about
  end

  def index
      @bookers = Booker.all
      @booker = Booker.new
  end

  def show
      @book = Booker.find(params[:id])
      @booker = Booker.new
      @user = @book.user
  end

  def create
      @book = Booker.new(booker_params)
      @book.user_id = current_user.id
       if @book.save
          flash[:notice] = "Book was successfully created."
          redirect_to booker_path(@book.id)
       else
          @bookers = Booker.all
          @booker = @book
          # binding pry
          render action: :index
      end
  end

  def edit
      @booker = Booker.find(params[:id])
  end

  def update
      @booker = Booker.find(params[:id])
      if @booker.update(booker_params)
         flash[:notice] = "Book was successfully updated."
         redirect_to booker_path(@booker.id)
      else
        render action: :edit
      end
  end

  def destroy
      booker = Booker.find(params[:id])
      booker.destroy
      redirect_to bookers_path
  end

  before_action :correct_user, only: [:edit, :update]

  private
    def booker_params
        params.require(:booker).permit(:title, :body, :user_id)
    end

    def correct_user
    book = Booker.find(params[:id])
    if current_user != book.user
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
  		@user = User.find(params[:id])
  		@post_pages = @user.bookers
  		@booker = Booker.new
    end

    def edit
		  @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if@user.update(user_params)
	      redirect_to user_path(@user.id)
      else
        render :edit
      end
    end

    def index
      @booker = Booker.new
      @users = User.all
    end

    before_action :correct_user, only: [:edit, :update]

  private

    def user_params
    	params.require(:user).permit(:name, :profile_image, :user, :user_body)
    end

    def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookers/_list.html.erb
<div class="new-book-box">
	<h2>New book</h2>
		<%= form_for(booker) do |f| %>
		<div class="field">
			<%= f.label :title, "Title" %><br>
			<%= f.text_field :title,class: "book_title" %>
		</div>
		<div class="field">
			<%= f.label :body, "body" %><br>
			<%= f.text_area :body,class: "book_body" %>
		</div>
			<input class="btn btn-primary create-btn" type="submit" value="Create Box">
		<% end %>
</div>

app/views/bookers/about.html.erb
<div class="container">
    <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
</div>
<footer>
	<div class="container">
		<div class="low">
			<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
		</div>
	</div>
</footer>

app/views/bookers/edit.html.erb
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>
<div class="container">
  	<div class="low">
  		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<%= form_for(@booker) do |f| %>
				<div class="edit-title">
					<h4>Title</h4>
					<%= f.text_field :title, class:"book_title" %>
				</div>
				<div class="edit-body">
					<h4>body</h4>
					<%= f.text_area :body, class:"book_body" %>
				</div>
				<div>
					<%= f.submit 'Update Book' %>
				</div>
			<% end %>
				<div class="edit-box-bottom">
					<span class="edit-show"><%= link_to "show", booker_path(@booker.id), class: "show_#{@booker.id}" %>
					</span>
					<span class="edit-back"><%= link_to "Back", bookers_path, class: "back" %>
					</span>
				</div>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="low">
			<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
		</div>
	</div>
</footer>

app/views/bookers/index.html.erb
<div class="container">
	<div class="low">
		<div class="col-xs-3">
			<div class="profile-container">
				<%= render 'users/list', user: current_user %>
				<%= render 'bookers/list', booker: @booker %>
			</div>
		</div>

		<div class="col-xs-9">
			<h1>Books</h1>
			<div class="aa">
				<table class="table table-striped">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Body</th>
						</tr>
					</thead>
					<tbody>
						<% @bookers.each do |booker| %>
						<tr>
							<td><%= attachment_image_tag booker.user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg" %></td>
							<td><%= link_to booker.title, booker %></td>
							<td><%= booker.body %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="low">
			<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
		</div>
	</div>
</footer>

app/views/bookers/show.html.erb
<div class="container">
	<div class="low">
		<div class="col-xs-3">
			<div class="profile-container">
				<%= render 'users/list', user: @user %>
				<%= render 'bookers/list', booker: @booker %>
			</div>
		</div>
		<div class="col-xs-9">
			<% if flash[:notice] %>
				<div class="flash">
					<%= flash[:notice] %>
				</div>
			<% end %>
			<div class="show-box-top">
				<h2>Book detail</h2>
				 <table class="table table-striped">
					<thead>
						<tr>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= @book.title %></td>
							<td><%= @book.body %></td>
							<% if @book.user == current_user %>
								<td>
									<%= link_to edit_booker_path(@book.id), class: "btn btn-success btn-sm" do %>
  									<span>Edit</span>
									<% end %>
								</td>
								<td>
									<%= link_to booker_path(@book.id), class: "btn btn-danger btn-sm destroy_#{@booker.id}",method: :delete,"data-confirm" => "本当に消しますか?" do %>
  									<span>Destroy</span>
									<% end %>
								</td>
							<% end %>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="low">
			<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
		</div>
	</div>
</footer>

app/views/bookers/top.html.erb
<div class="box">
	<div class="top">
		<div class="container">
			<div class="low">
				<div class="top-message col-md-offset-3 col-md-6">
					<h1>Welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>!!</span></h1>
					<p>In<span class="glyphicon glyphicon-book"><strong>Bookers</strong>,</span></p>
					<p>you can share and exchange  your opinions , inpressions , and emotions</p>
					<p> about varioius books!</p>
					<div class="login-menu">
						<a class="btn btn-info col-xs-10 col-xs-offset-1" href="/users/sign_in">Log in</a>
						<a class="btn btn-success col-xs-10 col-xs-offset-1" href="/users/sign_up">Sign Up</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<footer>
	<div class="container">
		<div class="low">
			<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
		</div>
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookers</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head>
<body>
  <header class="navbar navber-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span class="header-title">Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
          <% if user_signed_in? %>
            <li class="">
                <%= link_to user_path(current_user.id) do %>
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
                <% end %>
            </li>
            <li class="">
                <%= link_to users_path do %>
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Users
                <% end %>
            </li>
            <li class="">
                <%= link_to bookers_path do %>
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Bookes
                <% end %>
            </li>
            <li class="">
                <%= link_to destroy_user_session_path, method: :delete do %>
               <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> logout
                <% end %>

          <% else %>
          <li class="">
                <%= link_to root_path do %>
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
                <% end %>
            </li>
             <li class="">
                <%= link_to bookers_about_path do %>
                <span class="glyphicon glyphicon-link" aria-hidden="true"></span> About
                <% end %>
            </li>
            <li class="">
                <%= link_to "/users/sign_up" do %>
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> sign up
                <% end %>
            </li>
            <li class="">
                <%= link_to "/users/sign_in" do %>
                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> log in
                <% end %>
            </li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>
  <%= yield %>
</body>
</html>

app/views/users/_list.html.erb
<div class="profile-box">
	<h2>User info</h2>
		<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg" %>
		<table class="user-table">
			<tr>
				<th>name</th>
				<th class="profile-name"><%= user.name %></th>
			</tr>
			<tr>
				<th>introcuction</th>
				<th class="profile-Introduction"><%= user.user_body %></th>
			</tr>
		</table>
		<% if user.id == current_user.id %>
			<%= link_to edit_user_path(user), class: "btn btn-default btn-block" do %>
			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
			  <% end %>
		<% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="low">
    <div class="col-xs-3">
      <h1>User info</h1>
        <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@user.errors.count, "errors") %> prohibited this book from being saved:</h2>
              <ul>
              <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
              </ul>
          </div>
    <% end %>
          <div class="user-edit-name">
            <h4>name</h4>
            <%= f.text_field :name %>
          </div>
          <div class="user-edit-image">
            <h4>image</h4>
            <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg" %>

          <%= f.attachment_field :profile_image %>
          </div>
          <div class="user-edit-body">
            <h4>Introduction</h4>
            <%= f.text_area :user_body %>
          </div>
        <div>
          <%= f.submit 'Update Book' %>
        </div>
        <% end %>
    </div>
  </div>
</div>
<footer>
  <div class="container">
    <div class="low">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/index.html.erb
<div class="container">
	<div class="low">
		<div class="col-xs-3">
			<div class="profile-container">
				<%= render 'users/list', user: current_user %>
				<%= render 'bookers/list', booker: @booker %>
			</div>
		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
				<table class="table table-striped">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg" %></td>
							<td><%= user.name %></td>
							<td><%= link_to 'show', user_path(user) %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="low">
			<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
		</div>
	</div>
</footer>

app/views/users/show.html.erb
<div class="container">
	<div class="low">
		<div class="col-xs-3">
			<div class="profile-container">
				<%= render 'users/list', user: @user %>
				<%= render 'bookers/list', booker: @booker %>
			</div>
		</div>
		<div class="col-xs-9">
			<div class="user-index">
				<h2>Books</h2>
					<table class="table table-striped">
						<thead>
							<tr>
								<th></th>
								<th>Title</th>
								<th>Opinion</th>
							</tr>
						</thead>
						<tbody>
							<% @post_pages.each do |booker| %>
							<tr>
								<td><%= attachment_image_tag booker.user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg" %></td>
								<td><%= link_to booker.title, booker %></td>
								<td><%= booker.body %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
			</div>
		</div>
	</div>
</div>
<footer>
	<div class="container">
		<div class="low">
			<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
		</div>
	</div>
</footer>